name: 'HepLib Website'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'  # To Avoid Loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2

    - name: HepLib website
      uses: ZanderZhao/gitbook-action@master  
      with:
        token: ${{ secrets.PERSONAL_TOKEN }} 
        time_zone: Asia/Shanghai
        source_branch: master
        source_edit_time: true
        publish_commit_message: ${{ github.event.head_commit.message }}
        publish_branch: master
        publish_dir: docs
